export const works = [
  {
    id: 1,
    title: "portfolio",
    description: "My portfolio website",
    technology: ["React", "HTML5", "CSS3", "Bootstrap"],
    code: "https://github.com/Sandip-Z/portfolio",
    live: "http://www.sandipsatyal.com.np",
    detail: true,
  },
  {
    id: 5,
    title: "My Movies",
    description:
      "Create a watch, watching and watched list for favorite movies and share it with your friends.",
    technology: ["MongoDB", "Express.js", "React", "Node"],
    code: "https://github.com/Sandip-Z/notebook.io_landing_page",
    live: "s",
    detail: true,
  },
  {
    id: 4,
    title: "Presak Distribution",
    description:
      "Help the company manage its distibution all across the country",
    technology: ["React", "React Bootstrap", "Redux"],
    // code: "https://github.com/Sandip-Z/notebook.io_landing_page",
    // live: "s",
    detail: true,
  },
  {
    id: 2,
    title: "Goodvibes Admin Panel",
    description: "Helps check your website's accessibility, broken links etc",
    technology: ["React", "Redux", "Ant Design", "Chart.js"],
    // code: "https://github.com/Sandip-Z/portfolio",
    // live: "http://www.sandipsatyal.com.np",
    detail: true,
    images: ["gv_login.png", "gv_dashboard.png", "gv_page.png", "gv_form.png"],
  },
  {
    id: 3,
    title: "Notebook.io",
    description: "Landing page, login page and register for notebook.io",
    technology: ["HTML5", "CSS3", "SASS"],
    code: "https://github.com/Sandip-Z/notebook.io_landing_page",
    live: "s",
    detail: true,
    images: ["nb_land.png", "nb_login.png", "nb_register.png"],
  },
  {
    id: 6,
    title: "Tour",
    description: "Lorem ipusum...",
    technology: ["HTML5", "CSS3", "SASS", "Javascript"],
    code: "",
    live: "",
    detail: true,
  },
  // {
  //   id: 6,
  //   title: "Tour",
  //   description: "Lorem ipusum...",
  //   technology: ["HTML5", "CSS3", "SASS", "Javascript"],
  //   code: "",
  //   live: "",
  //   detail: true,
  // },
  // {
  //   id: 5,
  //   title: "Resource.io",
  //   description:
  //     "Helps users keep track of their study materials topic or subject wise",
  //   technology: ["MongoDB", "Express.js", "React.js", "Node"],
  //   code: "https://github.com/Sandip-Z/notebook.io_landing_page",
  //   live: "s",
  //   detail: true,
  // },
  // {
  //   id: 6,
  //   title: "Tour",
  //   description: "Lorem ipusum...",
  //   technology: ["HTML5", "CSS3", "SASS", "Javascript"],
  //   code: "",
  //   live: "",
  //   detail: true,
  // },
  // {
  //   id: 5,
  //   title: "Resource.io",
  //   description:
  //     "Helps users keep track of their study materials topic or subject wise",
  //   technology: ["MongoDB", "Express.js", "React.js", "Node"],
  //   code: "https://github.com/Sandip-Z/notebook.io_landing_page",
  //   live: "s",
  //   detail: true,
  // },
];
